### ISSUE TITLE
torchscript files are not provided.

### ISSUE THREAD

**Issue by hassaanhashmi** [ZHEQIUSHUI/monodepth2-cpp#1]
Hi, I am trying to implement the monodepth2 in libtorch for a RGB-D SLAM problem. Could you please upload the `*.cpt` files as well.

**Comment by hassaanhashmi** [comment]
The link you shared is not working for me.

**Comment by ZHEQIUSHUI** [comment]
i cant upload to Google drive because my vpn is death...so i will upload to Google drive when i can use my vpn,sorry

**Comment by hassaanhashmi** [comment]
Thank you for the reply and taking the trouble. I'll wait then.

**Comment by vmbatlle** [comment]
Hello. I'm sorry to comment on this closed issue, but there is no way to download the Baidu folder from Europe. I only need the two files that you use in the example:

- `monodepth2/models/mono+stereo_1024x320/encoder.cpt`
- `monodepth2/models/mono+stereo_1024x320/decoder.cpt`

If you could upload them to this or another repository, it'd help me a lot with my final project on Computer Science. Thank you in advance.

**[EDIT]**
Please, ignore my comment. I've finally managed to edit Monodepth2's `networks/*.py` so as to generate the TorchScript files. Thank you anyways.
